site_name: Ray
theme:
  name: material
  logo: 'images/ray-logo.png'
  favicon: 'images/favicon.ico'
  palette:
    primary: white
    accent: blue
  features:
    - navigation.sections
    - content.tabs.link
extra_css:
    - stylesheets/extra.css

markdown_extensions:
  # Syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Images
  - attr_list
  - md_in_html

nav:
  - Getting started:
    - 'Welcome to Ray documentations': index.md
    - 'What and why': what-and-why/what-and-why-ray.md
  - Ray for distributed compute:
    - 'Getting started': ray-distributed-compute/getting-started.md
    - 'Key concepts': ray-distributed-compute/key-concepts.md
    - 'Tutorials': ray-distributed-compute/tutorials.md
  - Ray for ML:
    - 'Overview': ray-ml/overview.md
    - 'Ray Data': 
      - 'Getting started': ray-ml/ray-data/getting-started.md
      - 'Key concepts': ray-ml/ray-data/key-concepts.md
      - 'Tutorials': ray-ml/ray-data/tutorials.md
    - 'Ray Train': 
      - 'Getting started': ray-ml/ray-train/getting-started.md
      - 'Key concepts': ray-ml/ray-train/key-concepts.md
      - 'Tutorials': ray-ml/ray-train/tutorials.md
    - 'RLlib': 
      - 'Getting started': ray-ml/ray-rllib/getting-started.md
      - 'Key concepts': ray-ml/ray-rllib/key-concepts.md
      - 'Tutorials': ray-ml/ray-rllib/tutorials.md
    - 'Ray Tune': 
      - 'Getting started': ray-ml/ray-tune/getting-started.md
      - 'Key concepts': ray-ml/ray-tune/key-concepts.md
      - 'Tutorials': ray-ml/ray-tune/tutorials.md
    - 'Ray Workflows': 
      - 'Getting started': ray-ml/ray-workflows/getting-started.md
      - 'Key concepts': ray-ml/ray-workflows/key-concepts.md
      - 'Tutorials': ray-ml/ray-workflows/tutorials.md
    - 'Ray Serve': 
      - 'Getting started': ray-ml/ray-serve/getting-started.md
      - 'Key concepts': ray-ml/ray-serve/key-concepts.md
      - 'Tutorials': ray-ml/ray-serve/tutorials.md
  - Deploy Ray:
    - 'Getting started': ray-deployment/getting-started.md
    - 'Key concepts': ray-deployment/key-concepts.md
    - 'Tutorials': ray-deployment/tutorials.md
  - API references:
    - 'Ray Core': api-references/ray-core.md
    - 'Ray Data': api-references/ray-data.md
    - 'Ray Train': api-references/ray-train.md
    - 'RLlib': api-references/ray-rllib.md
    - 'Ray Tune': api-references/ray-tune.md
    - 'Ray Workflows': api-references/ray-workflows.md
    - 'Ray Serve': api-references/ray-serve.md
  - Contributor guide:
    - 'Getting involved / Contributing': contributor-guide/getting-involved.md

      